/** Единый каталог SFX — id, теги, loop, громкость по умолчанию */
export const SFX_CATALOG_VERSION = 2;

export const SFX_CATALOG = [
  {id: "rain-light", tags: ["rain", "weather", "outdoor", "calm", "night"], loop: true, defaultVolume: 0.26},
  {id: "rain-heavy", tags: ["rain", "storm", "weather", "dramatic", "outdoor"], loop: true, defaultVolume: 0.3},
  {id: "rain-roof", tags: ["rain", "indoor", "attic", "house", "night"], loop: true, defaultVolume: 0.28},
  {id: "thunder-distant", tags: ["thunder", "storm", "weather", "dramatic"], loop: false, defaultVolume: 0.42},
  {id: "thunder-close", tags: ["thunder", "storm", "scary", "dramatic"], loop: false, defaultVolume: 0.5},
  {id: "wind-soft", tags: ["wind", "outdoor", "calm", "night", "trees"], loop: true, defaultVolume: 0.22},
  {id: "wind-gust", tags: ["wind", "outdoor", "dramatic", "cold"], loop: false, defaultVolume: 0.35},
  {id: "wind-howling", tags: ["wind", "scary", "night", "storm", "attic"], loop: true, defaultVolume: 0.3},
  {id: "storm-ambient", tags: ["storm", "rain", "wind", "dramatic", "outdoor"], loop: true, defaultVolume: 0.32},
  {id: "birds-day", tags: ["birds", "morning", "park", "calm", "outdoor"], loop: true, defaultVolume: 0.2},
  {id: "crickets-night", tags: ["crickets", "night", "summer", "outdoor", "calm"], loop: true, defaultVolume: 0.24},
  {id: "owl", tags: ["owl", "night", "forest", "scary", "mystery"], loop: false, defaultVolume: 0.32},
  {id: "ocean-waves", tags: ["ocean", "beach", "waves", "calm", "outdoor"], loop: true, defaultVolume: 0.26},
  {id: "river-soft", tags: ["water", "river", "calm", "nature", "outdoor"], loop: true, defaultVolume: 0.22},
  {id: "water-drip", tags: ["drip", "water", "basement", "bathroom", "tension"], loop: true, defaultVolume: 0.28},
  {id: "fire-crackle", tags: ["fire", "warm", "home", "calm", "winter"], loop: true, defaultVolume: 0.24},
  {id: "snow-wind", tags: ["snow", "wind", "cold", "winter", "outdoor"], loop: true, defaultVolume: 0.24},
  {id: "traffic-distant", tags: ["city", "traffic", "urban", "street", "day"], loop: true, defaultVolume: 0.2},
  {id: "traffic-rain", tags: ["city", "rain", "traffic", "urban", "night"], loop: true, defaultVolume: 0.24},
  {id: "city-night", tags: ["city", "night", "urban", "ambient", "calm"], loop: true, defaultVolume: 0.22},
  {id: "subway-pass", tags: ["subway", "train", "urban", "transit"], loop: false, defaultVolume: 0.38},
  {id: "cafe-murmur", tags: ["cafe", "crowd", "indoor", "calm", "day"], loop: true, defaultVolume: 0.18},
  {id: "office-hum", tags: ["office", "indoor", "ambient", "work", "calm"], loop: true, defaultVolume: 0.16},
  {id: "elevator-ding", tags: ["elevator", "indoor", "building", "urban"], loop: false, defaultVolume: 0.34},
  {id: "siren-distant", tags: ["siren", "city", "emergency", "dramatic", "night"], loop: false, defaultVolume: 0.36},
  {id: "construction-distant", tags: ["construction", "city", "urban", "day"], loop: true, defaultVolume: 0.18},
  {id: "door-creak-slow", tags: ["door", "creak", "scary", "house", "mystery"], loop: false, defaultVolume: 0.4},
  {id: "door-creak-fast", tags: ["door", "creak", "fast", "tension", "house"], loop: false, defaultVolume: 0.38},
  {id: "door-slam-soft", tags: ["door", "slam", "house", "dramatic"], loop: false, defaultVolume: 0.42},
  {id: "door-knock", tags: ["knock", "door", "tension", "visitor", "house"], loop: false, defaultVolume: 0.44},
  {id: "doorbell", tags: ["doorbell", "door", "house", "visitor", "day"], loop: false, defaultVolume: 0.36},
  {id: "footsteps-wood-slow", tags: ["footsteps", "wood", "slow", "suspense", "indoor"], loop: false, defaultVolume: 0.34},
  {id: "footsteps-wood-fast", tags: ["footsteps", "wood", "fast", "run", "panic"], loop: false, defaultVolume: 0.36},
  {id: "footsteps-stairs", tags: ["footsteps", "stairs", "house", "suspense", "indoor"], loop: false, defaultVolume: 0.35},
  {id: "footsteps-concrete", tags: ["footsteps", "concrete", "outdoor", "yard", "night"], loop: false, defaultVolume: 0.34},
  {id: "floor-creak-1", tags: ["creak", "floor", "wood", "house", "suspense"], loop: false, defaultVolume: 0.38},
  {id: "floor-creak-2", tags: ["creak", "floor", "wood", "old", "mystery"], loop: false, defaultVolume: 0.36},
  {id: "attic-creak", tags: ["attic", "creak", "wood", "scary", "house", "mystery"], loop: false, defaultVolume: 0.4},
  {id: "basement-drip", tags: ["basement", "drip", "water", "dark", "tension"], loop: true, defaultVolume: 0.26},
  {id: "window-rattle", tags: ["window", "wind", "old", "house", "night"], loop: false, defaultVolume: 0.32},
  {id: "glass-tap", tags: ["glass", "tap", "window", "tension", "surprise"], loop: false, defaultVolume: 0.3},
  {id: "heartbeat-calm", tags: ["heartbeat", "tension", "body", "calm"], loop: true, defaultVolume: 0.22},
  {id: "heartbeat-fast", tags: ["heartbeat", "fear", "panic", "tension"], loop: true, defaultVolume: 0.28},
  {id: "breath-nervous", tags: ["breath", "fear", "tension", "human"], loop: false, defaultVolume: 0.3},
  {id: "gasp", tags: ["gasp", "surprise", "shock", "human"], loop: false, defaultVolume: 0.38},
  {id: "whisper-wind", tags: ["whisper", "wind", "scary", "mystery", "supernatural"], loop: true, defaultVolume: 0.2},
  {id: "scratch-wall", tags: ["scratch", "wall", "scary", "horror", "tension"], loop: false, defaultVolume: 0.34},
  {id: "metal-clang-soft", tags: ["metal", "clang", "industrial", "basement"], loop: false, defaultVolume: 0.36},
  {id: "chain-rattle", tags: ["chain", "metal", "scary", "basement", "attic"], loop: false, defaultVolume: 0.34},
  {id: "static-radio", tags: ["static", "radio", "old", "mystery", "tech"], loop: true, defaultVolume: 0.16},
  {id: "electric-hum", tags: ["electric", "hum", "indoor", "basement", "tech"], loop: true, defaultVolume: 0.18},
  {id: "phone-vibrate", tags: ["phone", "vibrate", "tech", "notification"], loop: false, defaultVolume: 0.32},
  {id: "dog-bark-distant", tags: ["dog", "bark", "outdoor", "yard", "night"], loop: false, defaultVolume: 0.3},
  {id: "dog-bark-close", tags: ["dog", "bark", "close", "alert", "outdoor"], loop: false, defaultVolume: 0.4},
  {id: "cat-meow", tags: ["cat", "pet", "home", "night"], loop: false, defaultVolume: 0.32},
  {id: "crow", tags: ["crow", "bird", "scary", "omen", "outdoor"], loop: false, defaultVolume: 0.34},
  {id: "mice-scurry", tags: ["mice", "scurry", "attic", "basement", "scary"], loop: false, defaultVolume: 0.28},
  {id: "laughter-distant", tags: ["laughter", "crowd", "party", "creepy", "distant"], loop: false, defaultVolume: 0.24},
  {id: "crowd-murmur", tags: ["crowd", "murmur", "public", "indoor", "event"], loop: true, defaultVolume: 0.18},
  {id: "clock-tick", tags: ["clock", "tick", "night", "tension", "indoor"], loop: true, defaultVolume: 0.2},
  {id: "clock-chime", tags: ["clock", "chime", "night", "old", "house"], loop: false, defaultVolume: 0.34},
  {id: "room-tone-warm", tags: ["room", "ambient", "home", "calm", "indoor"], loop: true, defaultVolume: 0.14},
  {id: "room-tone-cold", tags: ["room", "ambient", "empty", "tension", "indoor"], loop: true, defaultVolume: 0.14},
  {id: "basement-ambience", tags: ["basement", "dark", "ambient", "tension", "indoor"], loop: true, defaultVolume: 0.2},
  {id: "attic-ambience", tags: ["attic", "dark", "ambient", "mystery", "indoor"], loop: true, defaultVolume: 0.2},
  {id: "forest-ambience", tags: ["forest", "nature", "outdoor", "calm", "day"], loop: true, defaultVolume: 0.22},
  {id: "park-ambience", tags: ["park", "outdoor", "day", "calm", "nature"], loop: true, defaultVolume: 0.2},
  {id: "yard-night", tags: ["yard", "night", "outdoor", "suburban", "calm"], loop: true, defaultVolume: 0.2},
  {id: "kitchen-hum", tags: ["kitchen", "home", "fridge", "indoor", "calm"], loop: true, defaultVolume: 0.16},
  {id: "kettle-boil", tags: ["kettle", "kitchen", "home", "calm"], loop: true, defaultVolume: 0.2},
  {id: "typing-distant", tags: ["typing", "keyboard", "office", "ambient", "indoor"], loop: true, defaultVolume: 0.14},
  {id: "drizzle-soft", tags: ["rain", "weather", "calm", "outdoor", "night"], loop: true, defaultVolume: 0.22},
  {id: "hail-rattle", tags: ["hail", "storm", "weather", "dramatic", "outdoor"], loop: true, defaultVolume: 0.28},
  {id: "fog-damp", tags: ["fog", "damp", "mystery", "outdoor", "cold"], loop: true, defaultVolume: 0.2},
  {id: "car-pass-distant", tags: ["car", "traffic", "street", "urban", "night"], loop: false, defaultVolume: 0.34},
  {id: "car-interior-hum", tags: ["car", "interior", "road", "travel", "ambient"], loop: true, defaultVolume: 0.18},
  {id: "bus-idle", tags: ["bus", "transit", "urban", "street", "day"], loop: true, defaultVolume: 0.2},
  {id: "train-distant", tags: ["train", "transit", "distant", "urban", "night"], loop: false, defaultVolume: 0.32},
  {id: "airplane-distant", tags: ["airplane", "sky", "travel", "distant", "outdoor"], loop: false, defaultVolume: 0.3},
  {id: "bicycle-bell", tags: ["bicycle", "bell", "street", "day", "urban"], loop: false, defaultVolume: 0.3},
  {id: "hospital-hall", tags: ["hospital", "hall", "indoor", "tension", "quiet"], loop: true, defaultVolume: 0.16},
  {id: "school-hallway", tags: ["school", "hallway", "indoor", "day", "youth"], loop: true, defaultVolume: 0.18},
  {id: "supermarket", tags: ["supermarket", "store", "indoor", "day", "urban"], loop: true, defaultVolume: 0.18},
  {id: "restaurant-ambience", tags: ["restaurant", "cafe", "indoor", "evening", "calm"], loop: true, defaultVolume: 0.2},
  {id: "bar-murmur", tags: ["bar", "night", "crowd", "indoor", "urban"], loop: true, defaultVolume: 0.22},
  {id: "library-quiet", tags: ["library", "quiet", "indoor", "calm", "study"], loop: true, defaultVolume: 0.12},
  {id: "shower-running", tags: ["shower", "water", "bathroom", "home", "indoor"], loop: true, defaultVolume: 0.24},
  {id: "pool-splashes", tags: ["pool", "water", "splash", "summer", "outdoor"], loop: true, defaultVolume: 0.22},
  {id: "leaves-rustle", tags: ["leaves", "wind", "forest", "autumn", "outdoor"], loop: true, defaultVolume: 0.22},
  {id: "waterfall-soft", tags: ["waterfall", "water", "nature", "calm", "outdoor"], loop: true, defaultVolume: 0.24},
  {id: "campfire-night", tags: ["campfire", "fire", "night", "outdoor", "calm"], loop: true, defaultVolume: 0.22},
  {id: "meadow-wind", tags: ["meadow", "wind", "nature", "day", "calm"], loop: true, defaultVolume: 0.2},
  {id: "keys-jingle", tags: ["keys", "door", "home", "arrival", "indoor"], loop: false, defaultVolume: 0.32},
  {id: "lock-click", tags: ["lock", "door", "security", "tension", "indoor"], loop: false, defaultVolume: 0.34},
  {id: "drawer-creak", tags: ["drawer", "creak", "furniture", "house", "indoor"], loop: false, defaultVolume: 0.3},
  {id: "dishes-clink", tags: ["dishes", "kitchen", "home", "day", "indoor"], loop: false, defaultVolume: 0.28},
  {id: "microwave-beep", tags: ["microwave", "kitchen", "beep", "home", "tech"], loop: false, defaultVolume: 0.3},
  {id: "washing-machine", tags: ["washing", "laundry", "home", "indoor", "ambient"], loop: true, defaultVolume: 0.18},
  {id: "cough-short", tags: ["cough", "human", "sick", "indoor", "tension"], loop: false, defaultVolume: 0.3},
  {id: "sigh", tags: ["sigh", "human", "sad", "tension", "emotion"], loop: false, defaultVolume: 0.28},
  {id: "laugh-soft", tags: ["laughter", "human", "warm", "comedy", "indoor"], loop: false, defaultVolume: 0.24},
  {id: "cry-distant", tags: ["cry", "sad", "human", "distant", "drama"], loop: false, defaultVolume: 0.22},
  {id: "computer-fan", tags: ["computer", "fan", "office", "tech", "indoor"], loop: true, defaultVolume: 0.14},
  {id: "notification-ding", tags: ["notification", "phone", "tech", "alert", "indoor"], loop: false, defaultVolume: 0.28},
  {id: "tv-muffled", tags: ["tv", "home", "indoor", "night", "ambient"], loop: true, defaultVolume: 0.16},
  {id: "cat-purr", tags: ["cat", "pet", "home", "calm", "indoor"], loop: true, defaultVolume: 0.2},
  {id: "frog-night", tags: ["frog", "night", "pond", "summer", "outdoor"], loop: true, defaultVolume: 0.22},
  {id: "horror-drone-low", tags: ["horror", "drone", "scary", "tension", "mystery"], loop: true, defaultVolume: 0.18},
  {id: "wind-chimes", tags: ["chimes", "wind", "calm", "home", "day"], loop: true, defaultVolume: 0.18},
  {id: "crowd-cheer-distant", tags: ["crowd", "cheer", "stadium", "distant", "outdoor"], loop: false, defaultVolume: 0.26},
  {id: "neon-hum", tags: ["neon", "city", "night", "urban", "ambient"], loop: true, defaultVolume: 0.16},
  {id: "printer", tags: ["printer", "office", "tech", "work", "indoor"], loop: false, defaultVolume: 0.26},
  {id: "phone-ring", tags: ["phone", "ring", "call", "alert", "indoor"], loop: false, defaultVolume: 0.34},
  {id: "alley-echo", tags: ["alley", "echo", "city", "night", "urban"], loop: true, defaultVolume: 0.2},
  {id: "market-murmur", tags: ["market", "crowd", "outdoor", "day", "urban"], loop: true, defaultVolume: 0.2},
  {id: "church-bells-distant", tags: ["bells", "church", "distant", "day", "outdoor"], loop: false, defaultVolume: 0.3},
  {id: "toilet-flush", tags: ["toilet", "bathroom", "water", "home", "indoor"], loop: false, defaultVolume: 0.32},
  {id: "garage-door", tags: ["garage", "door", "motor", "house", "suburban"], loop: false, defaultVolume: 0.36},
  {id: "sprinkler", tags: ["sprinkler", "yard", "water", "summer", "suburban"], loop: true, defaultVolume: 0.2},
  {id: "vacuum-cleaner", tags: ["vacuum", "cleaning", "home", "day", "indoor"], loop: true, defaultVolume: 0.2},
  {id: "baby-cry-distant", tags: ["baby", "cry", "home", "distant", "tension"], loop: false, defaultVolume: 0.24},
];

export const getSfxCatalogMap = () => new Map(SFX_CATALOG.map((item) => [item.id, item]));

export const getSfxCatalogIds = () => SFX_CATALOG.map((item) => item.id);
